import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFExportData {
  query: string;
  answer: string;
  citations: string[];
  executionMode: string;
  totalRows: number;
  sqlExecuted: string;
  explanation: string;
  alerts: Array<{ type: string; message: string; severity: string }>;
  graphElementId: string;
  mapElementId: string;
  userRole: string;
  userName: string;
}

export const exportIntelligenceReport = async (data: PDFExportData): Promise<void> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  // Title Page / Header Section
  doc.setFillColor(11, 15, 25); // Slate-950 background for header banner
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(6, 182, 212); // Cyan accent
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('SIDDHI CRIME INTELLIGENCE WORKSPACE', margin, 18);
  
  doc.setFontSize(10);
  doc.setTextColor(156, 163, 175); // Slate text
  doc.text('KARNATAKA STATE POLICE | CONFIDENTIAL INVESTIGATION REPORT', margin, 24);

  // Divider line
  doc.setDrawColor(30, 41, 59); // Slate-800
  doc.setLineWidth(0.5);
  doc.line(margin, 45, pageWidth - margin, 45);

  // Metadata Panel
  doc.setTextColor(243, 244, 246); // Light gray
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'bold');
  doc.text('REPORT METADATA', margin, 52);

  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(156, 163, 175);
  doc.text(`Generated By: ${data.userName} (${data.userRole})`, margin, 58);
  doc.text(`Timestamp: ${new Date().toLocaleString()}`, margin, 64);
  doc.text(`Execution Mode: ${data.executionMode.toUpperCase()}`, margin, 70);
  doc.text(`Total Records Found: ${data.totalRows}`, margin, 76);

  // Target Query Box
  doc.setFillColor(15, 23, 42); // slate-900 card
  doc.setDrawColor(30, 41, 59);
  doc.rect(margin, 82, contentWidth, 18, 'FD');
  
  doc.setTextColor(6, 182, 212);
  doc.setFont('Helvetica', 'bold');
  doc.text('TARGET INQUIRY', margin + 4, 88);
  doc.setTextColor(243, 244, 246);
  doc.setFont('Helvetica', 'normal');
  doc.text(`"${data.query}"`, margin + 4, 94);

  // Conversational Summary
  let currentY = 110;
  doc.setTextColor(6, 182, 212);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('1. ANALYTICAL CONVERSATIONAL SUMMARY', margin, currentY);
  currentY += 6;

  doc.setTextColor(243, 244, 246);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);

  const answerParagraphs = data.answer.split('\n');
  for (const para of answerParagraphs) {
    if (!para.trim()) continue;
    const splitText = doc.splitTextToSize(para, contentWidth);
    
    // Check page overflow
    if (currentY + splitText.length * 5 > pageHeight - 20) {
      doc.addPage();
      currentY = 20;
    }
    
    doc.text(splitText, margin, currentY);
    currentY += splitText.length * 5 + 3;
  }

  // Alerts
  if (data.alerts && data.alerts.length > 0) {
    if (currentY > pageHeight - 40) {
      doc.addPage();
      currentY = 20;
    }
    
    doc.setTextColor(239, 68, 68); // Red / warning
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('ACTIVE SYSTEM ALERTS', margin, currentY);
    currentY += 6;
    
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);
    for (const alert of data.alerts) {
      const alertMsg = `[${alert.type} - ${alert.severity}] ${alert.message}`;
      const splitAlert = doc.splitTextToSize(alertMsg, contentWidth);
      doc.text(splitAlert, margin, currentY);
      currentY += splitAlert.length * 4.5 + 2;
    }
    currentY += 3;
  }

  // Citations
  if (data.citations && data.citations.length > 0) {
    if (currentY > pageHeight - 30) {
      doc.addPage();
      currentY = 20;
    }
    doc.setTextColor(6, 182, 212);
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('EVIDENCE CITATIONS', margin, currentY);
    currentY += 6;
    doc.setFont('Helvetica', 'normal');
    doc.setTextColor(243, 244, 246);
    doc.setFontSize(9);
    doc.text(`Verified references: ${data.citations.join(', ')}`, margin, currentY);
    currentY += 10;
  }

  // Evidence SQL Explanation
  if (currentY > pageHeight - 45) {
    doc.addPage();
    currentY = 20;
  }
  doc.setTextColor(6, 182, 212);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2. EXPLAINABILITY & AUDIT METRICS', margin, currentY);
  currentY += 6;
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(9);
  doc.text(`Explanation: ${data.explanation}`, margin, currentY);
  currentY += 5;
  doc.text('SQL Executed:', margin, currentY);
  currentY += 4;
  doc.setFillColor(15, 23, 42);
  doc.setFont('Courier', 'normal');
  doc.setFontSize(8);
  const sqlSplit = doc.splitTextToSize(data.sqlExecuted, contentWidth - 4);
  
  doc.rect(margin, currentY, contentWidth, sqlSplit.length * 4 + 4, 'F');
  doc.setTextColor(34, 211, 238); // glowing cyan-400 for SQL
  doc.text(sqlSplit, margin + 2, currentY + 4);
  currentY += sqlSplit.length * 4 + 15;

  // Add screenshots (Network Graph & Heatmap)
  const graphEl = document.getElementById(data.graphElementId);
  const mapEl = document.getElementById(data.mapElementId);

  // Force Page Break for visuals
  doc.addPage();
  currentY = 20;
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(6, 182, 212);
  doc.text('3. CRIMINAL NETWORK SNAPSHOT (D3.JS GRAPH)', margin, currentY);
  currentY += 6;

  if (graphEl) {
    try {
      const graphCanvas = await html2canvas(graphEl, {
        backgroundColor: '#090d16',
        scale: 2,
      });
      const graphImg = graphCanvas.toDataURL('image/png');
      const imgHeight = (graphCanvas.height * contentWidth) / graphCanvas.width;
      doc.addImage(graphImg, 'PNG', margin, currentY, contentWidth, Math.min(imgHeight, 100));
      currentY += Math.min(imgHeight, 100) + 15;
    } catch (e) {
      doc.setTextColor(239, 68, 68);
      doc.text('[Failed to render Network Graph screenshot]', margin, currentY);
      currentY += 15;
    }
  } else {
    doc.setTextColor(156, 163, 175);
    doc.text('[Network Graph Visual Canvas Not Loaded]', margin, currentY);
    currentY += 15;
  }

  if (currentY > pageHeight - 110) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(6, 182, 212);
  doc.text('4. GEOSPATIAL CRIME HEATMAP (LEAFLET MAP)', margin, currentY);
  currentY += 6;

  if (mapEl) {
    try {
      const mapCanvas = await html2canvas(mapEl, {
        backgroundColor: '#090d16',
        useCORS: true,
        scale: 2,
      });
      const mapImg = mapCanvas.toDataURL('image/png');
      const imgHeight = (mapCanvas.height * contentWidth) / mapCanvas.width;
      doc.addImage(mapImg, 'PNG', margin, currentY, contentWidth, Math.min(imgHeight, 90));
    } catch (e) {
      doc.setTextColor(239, 68, 68);
      doc.text('[Failed to render Geospatial Heatmap screenshot]', margin, currentY);
    }
  } else {
    doc.setTextColor(156, 163, 175);
    doc.text('[Geospatial Heatmap Canvas Not Loaded]', margin, currentY);
  }

  // Save PDF
  doc.save(`SIDDHI_Intelligence_Report_${Date.now()}.pdf`);
};
